- name: Buat direktori keyrings jika belum ada
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Unduh dan simpan GPG key Kubernetes
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

- name: Tambahkan repository Kubernetes pkgs.k8s.io
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: kubernetes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages agar tidak auto-update
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    mark: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
