- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    create: yes
  with_items:
    - "192.168.56.10 master"
    - "192.168.56.11 node1"
    - "192.168.56.12 node2"

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab

- name: Enable kernel modules
  shell: |
    modprobe br_netfilter
    echo 'br_netfilter' > /etc/modules-load.d/k8s.conf

- name: Set sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Apply sysctl settings
  command: sysctl --system
